# Generated by Django 3.2.5 on 2021-07-24 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='This will be exposed to the outside world.', unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(help_text='who created.', on_delete=django.db.models.deletion.CASCADE, related_name='creators', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='who updated.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updators', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.basemodel')),
                ('mail_type', models.CharField(help_text='What type of mail.', max_length=255, unique=True, verbose_name='Mail Type')),
                ('subject', models.CharField(help_text='Subject of the mail.', max_length=255, unique=True, verbose_name='Subject')),
                ('mail_text', models.TextField(help_text='Body of the mail.', verbose_name='Mail Text')),
            ],
            options={
                'ordering': ['-id'],
            },
            bases=('common.basemodel',),
        ),
        migrations.AddIndex(
            model_name='emailtemplate',
            index=models.Index(fields=['mail_type', 'subject'], name='common_emai_mail_ty_704cb7_idx'),
        ),
    ]
